### ISSUE TITLE
line 7,8 on add.php

### ISSUE THREAD

**Issue by bennlongg** [pdkoding/Portfolio_v1#2]
Line 7 and 8 on add.php, consistency issue with variables :) 

https://github.com/pdkoding/Portfolio_v1/blob/4f41b683c712b118337d8a9e54d0f821f884c440/Project_II/about_html.php#L18

**Comment by pdkoding** [comment]
Same here,  my functions now work and after I make them consistent they will 100% stop, but will not that and not do the same inconsistency in the future Thanks :)
